---
apiVersion: 1
datasources:
  -
    database: postgres
    jsonData:
      connMaxLifetime: 14400
      maxIdleConns: 2
      maxOpenConns: 0
      postgresVersion: 903
      sslmode: disable
      timescaledb: false
    name: singles
    secureJsonData:
      password: secret
    type: postgres
    url: "postgres:5432"
    user: postgres
